# output "dns" {
#     value = {
#         "id": alicloud_dns.infra.name,
#         "domain_id": alicloud_dns.infra.domain_id,
#         "name": alicloud_dns.infra.name,
#         "group_id": alicloud_dns.infra.group_id,
#         "dns_server ": alicloud_dns.infra.dns_server,
#     }
# }
# output "dns_group" {
#     value = {
#         "id": alicloud_dns_group.infra.id,
#         "name": alicloud_dns_group.infra.name,
#     }
# }
output "dns_record" {
    value = {
        "inc": {
            "id": alicloud_dns_record.inc.id,
            "name": alicloud_dns_record.inc.name,
            "type": alicloud_dns_record.inc.type,
            "host_record": alicloud_dns_record.inc.host_record,
            "value": alicloud_dns_record.inc.value,
            "ttl": alicloud_dns_record.inc.ttl,
            "priority": alicloud_dns_record.inc.priority,
            "routing": alicloud_dns_record.inc.routing,
            "status": alicloud_dns_record.inc.status,
            "locked": alicloud_dns_record.inc.locked,
        },
        "www": {
            "id": alicloud_dns_record.www.id,
            "name": alicloud_dns_record.www.name,
            "type": alicloud_dns_record.www.type,
            "host_record": alicloud_dns_record.www.host_record,
            "value": alicloud_dns_record.www.value,
            "ttl": alicloud_dns_record.www.ttl,
            "priority": alicloud_dns_record.www.priority,
            "routing": alicloud_dns_record.www.routing,
            "status": alicloud_dns_record.www.status,
            "locked": alicloud_dns_record.www.locked,
        },
        "aliyundm-mail": {
            "id": alicloud_dns_record.aliyundm-mail.id,
            "name": alicloud_dns_record.aliyundm-mail.name,
            "type": alicloud_dns_record.aliyundm-mail.type,
            "host_record": alicloud_dns_record.aliyundm-mail.host_record,
            "value": alicloud_dns_record.aliyundm-mail.value,
            "ttl": alicloud_dns_record.aliyundm-mail.ttl,
            "priority": alicloud_dns_record.aliyundm-mail.priority,
            "routing": alicloud_dns_record.aliyundm-mail.routing,
            "status": alicloud_dns_record.aliyundm-mail.status,
            "locked": alicloud_dns_record.aliyundm-mail.locked,
        },
        "dmtrace": {
            "id": alicloud_dns_record.dmtrace.id,
            "name": alicloud_dns_record.dmtrace.name,
            "type": alicloud_dns_record.dmtrace.type,
            "host_record": alicloud_dns_record.dmtrace.host_record,
            "value": alicloud_dns_record.dmtrace.value,
            "ttl": alicloud_dns_record.dmtrace.ttl,
            "priority": alicloud_dns_record.dmtrace.priority,
            "routing": alicloud_dns_record.dmtrace.routing,
            "status": alicloud_dns_record.dmtrace.status,
            "locked": alicloud_dns_record.dmtrace.locked,
        },
        "mail-txt": {
            "id": alicloud_dns_record.mail-txt.id,
            "name": alicloud_dns_record.mail-txt.name,
            "type": alicloud_dns_record.mail-txt.type,
            "host_record": alicloud_dns_record.mail-txt.host_record,
            "value": alicloud_dns_record.mail-txt.value,
            "ttl": alicloud_dns_record.mail-txt.ttl,
            "priority": alicloud_dns_record.mail-txt.priority,
            "routing": alicloud_dns_record.mail-txt.routing,
            "status": alicloud_dns_record.mail-txt.status,
            "locked": alicloud_dns_record.mail-txt.locked,
        },
        "local": {
            "id": alicloud_dns_record.local.id,
            "name": alicloud_dns_record.local.name,
            "type": alicloud_dns_record.local.type,
            "host_record": alicloud_dns_record.local.host_record,
            "value": alicloud_dns_record.local.value,
            "ttl": alicloud_dns_record.local.ttl,
            "priority": alicloud_dns_record.local.priority,
            "routing": alicloud_dns_record.local.routing,
            "status": alicloud_dns_record.local.status,
            "locked": alicloud_dns_record.local.locked,
        },
        "develop": {
            "id": alicloud_dns_record.develop.id,
            "name": alicloud_dns_record.develop.name,
            "type": alicloud_dns_record.develop.type,
            "host_record": alicloud_dns_record.develop.host_record,
            "value": alicloud_dns_record.develop.value,
            "ttl": alicloud_dns_record.develop.ttl,
            "priority": alicloud_dns_record.develop.priority,
            "routing": alicloud_dns_record.develop.routing,
            "status": alicloud_dns_record.develop.status,
            "locked": alicloud_dns_record.develop.locked,
        },
        "testing": {
            "id": alicloud_dns_record.testing.id,
            "name": alicloud_dns_record.testing.name,
            "type": alicloud_dns_record.testing.type,
            "host_record": alicloud_dns_record.testing.host_record,
            "value": alicloud_dns_record.testing.value,
            "ttl": alicloud_dns_record.testing.ttl,
            "priority": alicloud_dns_record.testing.priority,
            "routing": alicloud_dns_record.testing.routing,
            "status": alicloud_dns_record.testing.status,
            "locked": alicloud_dns_record.testing.locked,
        },
        "staging": {
            "id": alicloud_dns_record.staging.id,
            "name": alicloud_dns_record.staging.name,
            "type": alicloud_dns_record.staging.type,
            "host_record": alicloud_dns_record.staging.host_record,
            "value": alicloud_dns_record.staging.value,
            "ttl": alicloud_dns_record.staging.ttl,
            "priority": alicloud_dns_record.staging.priority,
            "routing": alicloud_dns_record.staging.routing,
            "status": alicloud_dns_record.staging.status,
            "locked": alicloud_dns_record.staging.locked,
        },
    }
}